name: EAS Build and Submit iOS
on:
  workflow_dispatch:
  # push:
  #  branches:
  #    - main
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Replace secrets in eas.json
        run: |
            sed -i 's/__APPLE_ID__/${{ secrets.APPLE_ID }}/g' eas.json
            sed -i 's/__APPLE_TEAM_ID__/${{ secrets.APPLE_TEAM_ID }}/g' eas.json
            sed -i 's/__ASC_APP_ID__/${{ secrets.ASC_APP_ID }}/g' eas.json

      - name: Write .env.local
        run: |
          echo $ENV_LOCAL_FILE >> .env.local
        shell: bash
        env:
          ENV_LOCAL_FILE : ${{secrets.ENV_LOCAL_FILE}}

      - name: Build on EAS and submit to App Store Connect
        run: eas build --platform ios --profile production --non-interactive --no-wait --auto-submit
