name: EAS Build and Submit iOS
on:
  workflow_dispatch:
  # push:
  #  branches:
  #    - main
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Escape and replace secrets in eas.json
        run: |
            escaped_apple_id=$(printf '%s\n' "${{ secrets.APPLE_ID }}" | sed 's/[\/&]/\\&/g')
            sed -i "s/__APPLE_ID__/$escaped_apple_id/g" eas.json
            sed -i 's/__APPLE_TEAM_ID__/${{ secrets.APPLE_TEAM_ID }}/g' eas.json
            sed -i 's/__ASC_APP_ID__/${{ secrets.ASC_APP_ID }}/g' eas.json
            sed -i 's/__EXPO_SECRET_ANDROID_PACKAGE__/${{ secrets.EXPO_SECRET_ANDROID_PACKAGE }}/g' eas.json
            sed -i 's/__EXPO_SECRET_APP_NAME__/${{ secrets.EXPO_SECRET_APP_NAME }}/g' eas.json
            sed -i 's/__EXPO_SECRET_EXTRA_EAS_PROJECT_ID__/${{ secrets.EXPO_SECRET_EXTRA_EAS_PROJECT_ID }}/g' eas.json
            sed -i 's/__EXPO_SECRET_IOS_BUNDLE_IDENTIFIER__/${{ secrets.EXPO_SECRET_IOS_BUNDLE_IDENTIFIER }}/g' eas.json
            sed -i 's/__EXPO_SECRET_OWNER__/${{ secrets.EXPO_SECRET_OWNER }}/g' eas.json
            sed -i 's/__EXPO_SECRET_UPDATES_URL__/${{ secrets.EXPO_SECRET_UPDATES_URL }}/g' eas.json

      - name: Build on EAS and submit to App Store Connect
        run: eas build --platform ios --profile production --non-interactive --no-wait --auto-submit
